### PR TITLE
Fix ZFS pool import delays by using cachefiles; Warn if no cachefile; Support multiple ZFS pools

### PR DESCRIPTION
**Pull request by globalcitizen**
Compared to the git HEAD of robbat2/genkernel, this pull request:
- fixes broken ZFS silent assumptions about a single cachefile existing with a certain name causing [Gentoo bug 627320](https://bugs.gentoo.org/627320) which many people have run in to
- improves user warnings regarding default import behavior (very slow) if no cachefile is set
- if a cachefile is set, imports it to the initramfs automatically
- adds support for multiple pools

### CODE REVIEW

**Comment by globalcitizen** [comment]
Three months and counting...

**Comment by ryao** [comment]
Unfortunately, I am very far behind on my bug mail. I am playing catch up and going through the backlog now. I expect to have this squashed within 72 hours.

**Comment by gyakovlev** [comment]
I've been running with this PR for a while and works fine.
It warns you to run zpool set chachefile=/something just before initramfs creation, which is nice.

but after boot all pools will reset cachefile value to default, not sure what forces it, maybe zfs itself.

just a quick note on this @ryao, as we discussed on IRC.
there is one gotcha if you have nvme drives for rootfs pool and use zpool cache and this PR.

here is an example zpool status
```Hack
  pool: example
 state: ONLINE
  scan: scrub repaired 0B in 0h0m with 0 errors on Wed May 16 19:37:26 2018
config:

        NAME                                                      STATE     READ WRITE CKSUM
        example                                                   ONLINE       0     0     0
          mirror-0                                                ONLINE       0     0     0
            nvme-Samsung_SSD_960_PRO_512GB_111111111111111-part1  ONLINE       0     0     0
            nvme-Samsung_SSD_960_PRO_512GB_222222222222222-part1  ONLINE       0     0     0
```

since drives are referenced via `/dev/disk/by-id`, that value ends up in the cachefile.

but, genkernel does not create `/dev/disk/by-id` entries for nvme drives yet.
so it does not help boot at all and it's still delayed until zfs falls back to scanning.

this file
https://github.com/robbat2/genkernel/blob/master/mdev/mdev.conf
and corresponding script will need to handle nvme as well.
there is bug for that 
https://bugs.gentoo.org/654680

and I'll try extending mdev config and storage-device script to support nvme disks.

**Comment by gyakovlev** [comment]
here is nvme mdev fix that goes well with this PR and zfs on nvme is bootable without any delay.
https://github.com/gyakovlev/genkernel/commit/e21fec6b87ca2ada59728f7db6961bf97ee22fff

**Comment by ryao** [comment]
So, I took a look at this and it is a bit odd. While it is true that each pool can have a separate cachefile, the normal and expected usage is to have all pools share a cachefile. This works, but potentially wastes space. If I don't have a better fix in the next 24 hours, I am okay with committing this, but I think we should squash it into a single commit.

**Comment by gyakovlev** [comment]
I also took a deeper look at it and it does not make sense anymore after doing research.
I have 4 pools and all can co-exist in default /etc/zfs/zpool.cache, that's the default behaviour.
And genkernel already copies zpool.cache to initrd.

So it looks the only thing we have to do to mitigate the delay is to pass `-c /etc/zfs/zpool.cache` to appropriate import calls.

To leave users a way to boot systems if cache becomes stale, we can probably add `dozfs=nocache` cmdline knob, similar to existing `dozfs=force`.
If that knob is found, genkernel should try to import pools like it does now, with delay, but without using cache.

Or even make it the other way around.
add `dozfs=cache` cmdline knob and pass `-c /etc/zfs/zpool.cache` to import if it's present.
and document that somewhere so users can workaround the boot delay passing it via bootloader.

@ryao what do you think?

**Comment by gyakovlev** [comment]
@ryao check this one
https://github.com/robbat2/genkernel/pull/17

WORKSFORME
and users have explicit choice using bootloader knob to use default cachefile or just wait 30+ seconds.

**Comment by ryao** [comment]
Just a FYI. This is fixed in sys-kernel/genkernel-9999. I plan to tag a new release after a few more planned improvements go into HEAD.

**Comment by robbat2** [comment]
please rebase this and include signed-off-by remarks in all commits

**Comment by gyakovlev** [comment]
@robbat2 you've merged alternative variant in https://github.com/robbat2/genkernel/pull/17

**Comment by robbat2** [comment]
@gyakovlev so I can just close this outright?

**Comment by gyakovlev** [comment]
@robbat2 yep

**Pull request closed without merging**
